"""Adapter protocol package for TulingResearch Plus."""

from tuling_research_plus.adapters.protocols import (
    AdapterCachePolicy,
    AdapterError,
    AdapterErrorCode,
    AdapterRequestContext,
    AdapterRetryPolicy,
    AdapterTimeoutPolicy,
    ApifyWebAdapter,
    ArxivAdapter,
    ArxivQuery,
    ArxivSearchResult,
    LLMCompletionRequest,
    LLMCompletionResult,
    OpenAICompatibleLLMAdapter,
    PDFConversionRequest,
    PDFConversionResult,
    PDFConverterAdapter,
    RateLimitPolicy,
    SemanticScholarAdapter,
    SemanticScholarPaperLookup,
    SemanticScholarPaperResult,
    WebFetchRequest,
    WebFetchResult,
)

__all__ = [
    "AdapterCachePolicy",
    "AdapterError",
    "AdapterErrorCode",
    "AdapterRequestContext",
    "AdapterRetryPolicy",
    "AdapterTimeoutPolicy",
    "ApifyWebAdapter",
    "ArxivAdapter",
    "ArxivQuery",
    "ArxivSearchResult",
    "LLMCompletionRequest",
    "LLMCompletionResult",
    "OpenAICompatibleLLMAdapter",
    "PDFConversionRequest",
    "PDFConversionResult",
    "PDFConverterAdapter",
    "RateLimitPolicy",
    "SemanticScholarAdapter",
    "SemanticScholarPaperLookup",
    "SemanticScholarPaperResult",
    "WebFetchRequest",
    "WebFetchResult",
]
