"""Static capability catalog collection."""

from __future__ import annotations

from turing_research_plus.capabilities.models import (
    CapabilityCategory,
    CapabilityEntry,
    CapabilityManifest,
    CapabilitySafetyLevel,
    CapabilityStatus,
)


def collect_core_capabilities() -> list[CapabilityEntry]:
    """Return the reviewable core capability catalog.

    This intentionally avoids runtime discovery, network calls, and tool
    execution. The catalog is a conservative public/release documentation aid.
    """

    return [
        CapabilityEntry(
            capability_id="evidence.ledger",
            name="VGGT Evidence Ledger",
            category=CapabilityCategory.EVIDENCE,
            tool_name="research.evidence_ledger",
            command="turing evidence ledger",
            module="turing_research_plus.vggt",
            input_model="EvidenceLedgerInput",
            output_model="EvidenceLedgerReport",
            safety_level=CapabilitySafetyLevel.LOCAL_REVIEW,
            docs=["docs/vggt-evidence-ledger.md"],
            tests=["tests/workflow/test_vggt_sprint1_end_to_end_fake.py"],
            related_skills=["turingresearch-master-orchestrator"],
        ),
        CapabilityEntry(
            capability_id="artifact.audit",
            name="Artifact Auditor",
            category=CapabilityCategory.ARTIFACT,
            tool_name="artifact.audit",
            command="turing artifact audit",
            module="turing_research_plus.artifact_audit",
            input_model="ArtifactAuditInput",
            output_model="ArtifactAuditReport",
            safety_level=CapabilitySafetyLevel.LOCAL_REVIEW,
            docs=["docs/artifact-auditor.md"],
            tests=["tests/unit/test_artifact_audit_models.py"],
            related_skills=["turingresearch-master-orchestrator"],
        ),
        CapabilityEntry(
            capability_id="visual.audit",
            name="Visual Evidence Auditor",
            category=CapabilityCategory.VISUAL,
            tool_name="visual.audit",
            command="turing visual audit",
            module="turing_research_plus.vggt",
            input_model="VisualEvidenceInput",
            output_model="VisualEvidenceAuditReport",
            safety_level=CapabilitySafetyLevel.LOCAL_REVIEW,
            docs=["docs/visual-evidence-auditor.md"],
            tests=["tests/workflow/test_vggt_visual_evidence_dry_run.py"],
            related_skills=["turingresearch-master-orchestrator"],
        ),
        CapabilityEntry(
            capability_id="advisor.pack",
            name="Advisor Pack Builder",
            category=CapabilityCategory.ADVISOR,
            tool_name="advisor.pack_build",
            command="turing advisor pack",
            module="turing_research_plus.advisor",
            input_model="AdvisorPackBuildInput",
            output_model="AdvisorPack",
            safety_level=CapabilitySafetyLevel.LOCAL_REVIEW,
            docs=["docs/advisor-pack-builder.md"],
            tests=["tests/unit/test_advisor_pack_builder.py"],
            related_skills=["turingresearch-master-orchestrator"],
        ),
        CapabilityEntry(
            capability_id="pdf.phase_b",
            name="PDF Figure/Table Extraction",
            category=CapabilityCategory.PDF,
            tool_name="pdf.extract_figures",
            command="turing pdf extract",
            module="turing_research.pdf",
            input_model="PDFAssetExtractionRequest",
            output_model="PDFAssetExtractionReport",
            safety_level=CapabilitySafetyLevel.LOCAL_REVIEW,
            docs=["docs/pdf_phase_b_figure_table_extraction.md"],
            tests=["tests/workflow/test_pdf_phase_b_fixture.py"],
            related_skills=["turingresearch-paper-figure-asset-pipeline"],
        ),
        CapabilityEntry(
            capability_id="paper.digest",
            name="Paper Digest Engine",
            category=CapabilityCategory.PAPER,
            tool_name="paper.digest",
            command="turing paper digest",
            module="turing_research_plus.paper_digest",
            input_model="PaperDigestRequest",
            output_model="PaperDigest",
            safety_level=CapabilitySafetyLevel.LOCAL_REVIEW,
            docs=["docs/paper-digest-engine.md"],
            tests=["tests/unit/test_digest_builder.py"],
            related_skills=["turingresearch-fusion-literature-survey"],
        ),
        CapabilityEntry(
            capability_id="citation.graph",
            name="Citation Graph Expansion",
            category=CapabilityCategory.CITATION,
            tool_name="graph.citation_graph_expand",
            command="turing citation graph",
            module="turing_research_plus.citation_graph",
            input_model="CitationGraphExpansionRequest",
            output_model="CitationGraph",
            safety_level=CapabilitySafetyLevel.LIVE_OPTIONAL,
            status=CapabilityStatus.IMPLEMENTED_MINIMAL,
            live_mode=True,
            fake_mode=True,
            required_env=["TURINGRESEARCH_ENABLE_LIVE_TESTS"],
            docs=["docs/citation-graph-expansion.md"],
            tests=["tests/unit/test_citation_graph_expander.py"],
            related_skills=["turingresearch-fusion-literature-survey"],
        ),
        CapabilityEntry(
            capability_id="collision.risk",
            name="Paper Collision Risk Detector",
            category=CapabilityCategory.COLLISION,
            tool_name="research.collision_risk_detect",
            command="turing paper collision-risk",
            module="turing_research_plus.collision",
            input_model="PaperComparisonInput",
            output_model="CollisionRiskReport",
            safety_level=CapabilitySafetyLevel.LOCAL_REVIEW,
            docs=["docs/paper-collision-risk-detector.md"],
            tests=["tests/unit/test_collision_risk_scoring.py"],
            related_skills=["turingresearch-fusion-literature-survey"],
        ),
        CapabilityEntry(
            capability_id="related_work.positioning",
            name="Related Work Positioning",
            category=CapabilityCategory.RELATED_WORK,
            tool_name="paper.related_work_position",
            command="turing paper position",
            module="turing_research_plus.related_work",
            input_model="RelatedWorkPositioningInput",
            output_model="RelatedWorkPositioningReport",
            safety_level=CapabilitySafetyLevel.LOCAL_REVIEW,
            docs=["docs/related-work-positioning-generator.md"],
            tests=["tests/unit/test_related_work_positioning.py"],
            related_skills=["turingresearch-fusion-literature-survey"],
        ),
        CapabilityEntry(
            capability_id="route.dsl",
            name="Experiment Route DSL",
            category=CapabilityCategory.ROUTE,
            tool_name="research.route_compile",
            command="turing route compile",
            module="turing_research_plus.experiment_route",
            input_model="ExperimentRouteSpec",
            output_model="CompiledExperimentRoute",
            safety_level=CapabilitySafetyLevel.LOCAL_REVIEW,
            docs=["docs/experiment-route-dsl.md"],
            tests=["tests/unit/test_experiment_route_compiler.py"],
            related_skills=["turingresearch-fusion-experiment-execution"],
        ),
        CapabilityEntry(
            capability_id="failure.taxonomy",
            name="Failure Taxonomy Engine",
            category=CapabilityCategory.FAILURE,
            tool_name="research.failure_classify",
            command="turing failure classify",
            module="turing_research_plus.failure",
            input_model="FailureAttributionInput",
            output_model="FailureAttributionReport",
            safety_level=CapabilitySafetyLevel.LOCAL_REVIEW,
            docs=["docs/failure-taxonomy-engine.md"],
            tests=["tests/unit/test_failure_classifier.py"],
            related_skills=["turingresearch-fusion-experiment-execution"],
        ),
        CapabilityEntry(
            capability_id="dashboard.modal_run",
            name="Modal Run Dashboard",
            category=CapabilityCategory.DASHBOARD,
            tool_name="dashboard.modal_run",
            command="turing dashboard modal-run",
            module="turing_research_plus.dashboard",
            input_model="RunIngestReport",
            output_model="ModalRunDashboard",
            safety_level=CapabilitySafetyLevel.LOCAL_REVIEW,
            docs=["docs/modal-run-dashboard.md"],
            tests=["tests/unit/test_run_dashboard_builder.py"],
            related_skills=["turingresearch-fusion-experiment-execution"],
        ),
        CapabilityEntry(
            capability_id="remote_artifacts.unified",
            name="Remote Artifact Integration",
            category=CapabilityCategory.REMOTE_ARTIFACT,
            tool_name="remote_artifacts.unify",
            command="turing remote-artifacts unify",
            module="turing_research_plus.remote_artifacts",
            input_model="RemoteArtifactSourceBundle",
            output_model="UnifiedRemoteArtifactReport",
            safety_level=CapabilitySafetyLevel.LIVE_OPTIONAL,
            live_mode=True,
            fake_mode=True,
            required_env=["TURINGRESEARCH_ENABLE_LIVE_TESTS"],
            docs=["docs/remote-artifact-integration.md"],
            tests=["tests/workflow/test_remote_artifact_integration_fake.py"],
            related_skills=["turingresearch-master-orchestrator"],
        ),
        CapabilityEntry(
            capability_id="handoff.bundle",
            name="Handoff Bundle Export / Import",
            category=CapabilityCategory.HANDOFF,
            tool_name="research.handoff_bundle_export",
            command="turing handoff bundle",
            module="turing_research_plus.handoff",
            input_model="HandoffExportRequest",
            output_model="HandoffBundleManifest",
            safety_level=CapabilitySafetyLevel.LOCAL_REVIEW,
            docs=["docs/handoff-bundle-export-import.md"],
            tests=["tests/unit/test_handoff_exporter.py"],
            related_skills=["turingresearch-master-orchestrator"],
        ),
        CapabilityEntry(
            capability_id="plugin.registry",
            name="Plugin Architecture",
            category=CapabilityCategory.PLUGIN,
            tool_name="plugins.registry_validate",
            command="turing plugins validate",
            module="turing_research_plus.plugins",
            input_model="PluginManifest",
            output_model="PluginValidationReport",
            safety_level=CapabilitySafetyLevel.LOCAL_REVIEW,
            docs=["docs/plugin-architecture.md"],
            tests=["tests/unit/test_plugin_validator.py"],
            related_skills=["turingresearch-qa-release"],
        ),
        CapabilityEntry(
            capability_id="workspace.registry",
            name="Multi-project Workspace",
            category=CapabilityCategory.WORKSPACE,
            tool_name="workspace.overview",
            command="turing workspace overview",
            module="turing_research_plus.workspace",
            input_model="Workspace",
            output_model="WorkspaceOverview",
            safety_level=CapabilitySafetyLevel.LOCAL_REVIEW,
            docs=["docs/multi-project-workspace.md"],
            tests=["tests/unit/test_workspace_registry.py"],
            related_skills=["turingresearch-master-orchestrator"],
        ),
    ]


def collect_capability_manifest(
    *,
    manifest_id: str = "turingresearch_capabilities",
) -> CapabilityManifest:
    """Build the default static capability manifest."""

    return CapabilityManifest(
        manifest_id=manifest_id,
        capabilities=collect_core_capabilities(),
        docs=["docs/tool-capability-manifest.md", "docs/capability-index.md"],
        tests=["tests/workflow/test_capability_manifest_fake.py"],
        requires_human_review=True,
        generated_from_static_catalog=True,
        starts_mcp_server=False,
        executes_tools=False,
    )
