"""Paper writing gate for TulingResearch Plus."""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field

from tuling_research_plus.artifacts.models import EvidenceRef
from tuling_research_plus.paper.figure_registry import (
    FigureAsset,
    FigureAssetRegistry,
    FigureAssetStatus,
)
from tuling_research_plus.paper.models import ArticleBlock, ExperimentReport


class PaperSection(StrEnum):
    """Structured paper sections generated by the writing pipeline."""

    ABSTRACT = "abstract"
    INTRODUCTION = "introduction"
    RELATED_WORK = "related_work"
    METHOD = "method"
    EXPERIMENTS = "experiments"
    RESULTS = "results"
    LIMITATIONS = "limitations"
    CONCLUSION = "conclusion"
    APPENDIX = "appendix"


class SectionReadinessStatus(StrEnum):
    """Section readiness status."""

    READY = "ready"
    BLOCKED = "blocked"


class PaperSectionStatus(BaseModel):
    """Readiness for one paper section."""

    model_config = ConfigDict(extra="forbid")

    section: PaperSection
    status: SectionReadinessStatus
    missing_items: list[str] = Field(default_factory=list)


class MissingEvidenceReport(BaseModel):
    """Missing evidence report returned when drafting is blocked."""

    model_config = ConfigDict(extra="forbid")

    missing_artifacts: list[str] = Field(default_factory=list)
    missing_evidence: list[str] = Field(default_factory=list)
    missing_figures: list[str] = Field(default_factory=list)
    blocked_reason: str | None = None

    def to_markdown(self) -> str:
        """Render the missing evidence report as Markdown."""

        lines = ["# TulingResearch Plus Missing Evidence Report", ""]
        if self.blocked_reason:
            lines.append(f"- Blocked reason: {self.blocked_reason}")
        lines.extend(["", "## Missing Artifacts"])
        lines.extend(f"- `{item}`" for item in self.missing_artifacts)
        lines.extend(["", "## Missing Evidence"])
        lines.extend(f"- {item}" for item in self.missing_evidence)
        lines.extend(["", "## Missing Figures"])
        lines.extend(f"- `{item}`" for item in self.missing_figures)
        return "\n".join(lines) + "\n"


class PaperDraftInput(BaseModel):
    """Input for paper.draft_generate."""

    model_config = ConfigDict(extra="forbid")

    available_artifacts: list[str] = Field(default_factory=list)
    article_blocks: list[ArticleBlock] = Field(default_factory=list)
    experiment_report: ExperimentReport | None = None
    figure_registry: FigureAssetRegistry | None = None
    stress_test_results: list[str] = Field(default_factory=list)


class PaperDraftOutput(BaseModel):
    """Output for paper.draft_generate."""

    model_config = ConfigDict(extra="forbid")

    blocked: bool
    draft_markdown: str | None = None
    section_status: list[PaperSectionStatus]
    missing_evidence_report: MissingEvidenceReport


REQUIRED_ARTIFACTS: tuple[str, ...] = (
    "ResearchBrief",
    "LiteratureSurveyArtifact",
    "MethodDesign",
    "ExperimentPlan",
    "ExperimentReport",
    "FigureAssetRegistry",
)


def generate_paper_draft(input_data: PaperDraftInput) -> PaperDraftOutput:
    """Generate a structured draft only when all hard gates pass."""

    missing_report = _missing_evidence_report(input_data)
    section_status = _section_status(input_data, missing_report)
    if (
        missing_report.missing_artifacts
        or missing_report.missing_evidence
        or missing_report.missing_figures
    ):
        return PaperDraftOutput(
            blocked=True,
            draft_markdown=None,
            section_status=section_status,
            missing_evidence_report=missing_report,
        )
    return PaperDraftOutput(
        blocked=False,
        draft_markdown=_draft_markdown(input_data),
        section_status=section_status,
        missing_evidence_report=missing_report,
    )


def paper_draft_generate(input_data: PaperDraftInput) -> dict[str, object]:
    """Thin paper.draft_generate wrapper."""

    return generate_paper_draft(input_data).model_dump(mode="json")


def paper_missing_evidence_for_draft(input_data: PaperDraftInput) -> dict[str, object]:
    """Thin missing evidence wrapper for paper writing gate."""

    return _missing_evidence_report(input_data).model_dump(mode="json")


def section_status_yaml(section_status: list[PaperSectionStatus]) -> str:
    """Render section status as simple YAML text."""

    lines = ["sections:"]
    for status in section_status:
        lines.append(f"  - section: {status.section.value}")
        lines.append(f"    status: {status.status.value}")
        lines.append("    missing_items:")
        lines.extend(f"      - {item}" for item in status.missing_items)
    return "\n".join(lines) + "\n"


def _missing_evidence_report(input_data: PaperDraftInput) -> MissingEvidenceReport:
    artifacts = set(input_data.available_artifacts)
    if input_data.experiment_report is not None:
        artifacts.add("ExperimentReport")
    if input_data.figure_registry is not None:
        artifacts.add("FigureAssetRegistry")
    missing_artifacts = [artifact for artifact in REQUIRED_ARTIFACTS if artifact not in artifacts]
    missing_evidence = _missing_block_evidence(input_data.article_blocks)
    missing_figures = _missing_figures(input_data.figure_registry)
    if input_data.experiment_report is None:
        missing_artifacts.append("ExperimentReport")
    if not _method_architecture_figures(input_data):
        missing_figures.append("method architecture figure")
    if not _experiment_tables(input_data):
        missing_figures.append("experiment table or metrics figure")
    if not input_data.stress_test_results:
        missing_evidence.append("Limitations section requires stress test results.")
    unique_missing_artifacts = _dedupe(missing_artifacts)
    blocked_reason = None
    if unique_missing_artifacts or missing_evidence or missing_figures:
        blocked_reason = "Paper draft generation blocked by missing required evidence."
    return MissingEvidenceReport(
        missing_artifacts=unique_missing_artifacts,
        missing_evidence=_dedupe(missing_evidence),
        missing_figures=_dedupe(missing_figures),
        blocked_reason=blocked_reason,
    )


def _section_status(
    input_data: PaperDraftInput,
    missing_report: MissingEvidenceReport,
) -> list[PaperSectionStatus]:
    statuses: list[PaperSectionStatus] = []
    for section in PaperSection:
        missing_items = _section_missing_items(section, input_data, missing_report)
        statuses.append(
            PaperSectionStatus(
                section=section,
                status=(
                    SectionReadinessStatus.BLOCKED
                    if missing_items
                    else SectionReadinessStatus.READY
                ),
                missing_items=missing_items,
            )
        )
    return statuses


def _section_missing_items(
    section: PaperSection,
    input_data: PaperDraftInput,
    missing_report: MissingEvidenceReport,
) -> list[str]:
    if section in {PaperSection.ABSTRACT, PaperSection.CONCLUSION, PaperSection.APPENDIX}:
        return list(missing_report.missing_artifacts)
    if section == PaperSection.METHOD and not _method_architecture_figures(input_data):
        return ["method architecture figure"]
    if section in {PaperSection.EXPERIMENTS, PaperSection.RESULTS}:
        missing = []
        if input_data.experiment_report is None:
            missing.append("ExperimentReport")
        if not _experiment_tables(input_data):
            missing.append("experiment table or metrics figure")
        return missing
    if section == PaperSection.LIMITATIONS and not input_data.stress_test_results:
        return ["stress test results"]
    return list(missing_report.missing_evidence)


def _draft_markdown(input_data: PaperDraftInput) -> str:
    evidence = _all_evidence(input_data)
    architecture_figures = _method_architecture_figures(input_data)
    experiment_figures = _experiment_tables(input_data)
    metrics = input_data.experiment_report.metrics if input_data.experiment_report else {}
    stress = "; ".join(input_data.stress_test_results)
    return "\n".join(
        [
            "# TulingResearch Plus Paper Draft",
            "",
            "## Abstract",
            f"Evidence-backed summary using {len(evidence)} EvidenceRef entries.",
            "",
            "## Introduction",
            _block_text(input_data.article_blocks, "research_brief"),
            "",
            "## Related Work",
            _block_text(input_data.article_blocks, "related_work"),
            "",
            "## Method",
            _block_text(input_data.article_blocks, "method_design"),
            (
                "Architecture figures: "
                f"{', '.join(asset.figure_id for asset in architecture_figures)}."
            ),
            "",
            "## Experiments",
            _block_text(input_data.article_blocks, "experiments"),
            (
                "Experiment tables and metrics figures: "
                f"{', '.join(asset.figure_id for asset in experiment_figures)}."
            ),
            "",
            "## Results",
            f"Reported metrics from ExperimentReport: {_format_metrics(metrics)}.",
            "",
            "## Limitations",
            f"Stress test results: {stress}.",
            "",
            "## Conclusion",
            "Conclusions are limited to the supplied ExperimentReport and EvidenceRef set.",
            "",
            "## Appendix",
            f"Evidence refs: {', '.join(ref.source_id for ref in evidence)}.",
            "",
        ]
    )


def _missing_block_evidence(blocks: list[ArticleBlock]) -> list[str]:
    missing = []
    for block in blocks:
        if not block.evidence:
            missing.append(f"ArticleBlock {block.block_id} has no EvidenceRef.")
    if not blocks:
        missing.append("ArticleBlocks are required.")
    return missing


def _missing_figures(registry: FigureAssetRegistry | None) -> list[str]:
    if registry is None:
        return ["FigureAsset registry"]
    return [
        asset.figure_id
        for asset in registry.assets
        if asset.status != FigureAssetStatus.READY or not asset.caption
    ]


def _method_architecture_figures(input_data: PaperDraftInput) -> list[FigureAsset]:
    if input_data.figure_registry is None:
        return []
    return [
        asset
        for asset in input_data.figure_registry.assets
        if "method_design" in asset.used_in_blocks
        and ("architecture" in asset.title.lower() or "architecture" in asset.figure_id.lower())
        and asset.status == FigureAssetStatus.READY
    ]


def _experiment_tables(input_data: PaperDraftInput) -> list[FigureAsset]:
    if input_data.figure_registry is None:
        return []
    return [
        asset
        for asset in input_data.figure_registry.assets
        if any(block in {"experiments", "paper_draft"} for block in asset.used_in_blocks)
        and ("table" in asset.title.lower() or "metric" in asset.title.lower())
        and asset.status == FigureAssetStatus.READY
    ]


def _block_text(blocks: list[ArticleBlock], block_kind: str) -> str:
    for block in blocks:
        if block.block_kind and block.block_kind.value == block_kind:
            return block.text
    return f"{block_kind} block supplied without draftable text."


def _all_evidence(input_data: PaperDraftInput) -> list[EvidenceRef]:
    evidence = [ref for block in input_data.article_blocks for ref in block.evidence]
    if input_data.experiment_report is not None:
        evidence.extend(input_data.experiment_report.evidence)
    return evidence


def _format_metrics(metrics: dict[str, object]) -> str:
    if not metrics:
        return "no metrics supplied"
    return ", ".join(f"{key}={value}" for key, value in metrics.items())


def _dedupe(values: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        if value not in seen:
            seen.add(value)
            result.append(value)
    return result
