"""Fake-first web fetch adapter."""

from __future__ import annotations

from datetime import UTC, datetime
from importlib.util import find_spec
from pathlib import Path
from typing import Any

from turing_research_plus.adapters.errors import AdapterError, AdapterErrorCode
from turing_research_plus.web.content_cache import WebContentCache
from turing_research_plus.web.html_extract import extract_title, html_to_text
from turing_research_plus.web.models import (
    RetrievalStatus,
    SourceType,
    WebFetchRequest,
    WebFetchResult,
)
from turing_research_plus.web.source_metadata import (
    build_cache_key,
    build_source_metadata,
    hash_text,
)

BLOCKED_HYGIENE = {"private", "restricted", "paywalled", "login_required", "unknown_private"}


class WebFetcher:
    """Fetch public web content with fixture/fake defaults and guarded live mode."""

    def __init__(
        self,
        *,
        cache: WebContentCache | None = None,
        client_factory: Any | None = None,
    ) -> None:
        self.cache = cache or WebContentCache()
        self.client_factory = client_factory

    def fetch(self, request: WebFetchRequest) -> WebFetchResult:
        """Fetch a URL without networking unless live mode is explicitly enabled."""

        url = str(request.url)
        blocked = self._source_hygiene_error(request)
        if blocked is not None:
            return self._error_result(
                request,
                RetrievalStatus.SOURCE_BLOCKED,
                warnings=[blocked.message],
            )

        cached = self.cache.get(url)
        if cached is not None and not cached.stale:
            return WebFetchResult(
                url=url,
                retrieval_status=RetrievalStatus.CACHE_HIT,
                retrieval_time=cached.retrieval_time,
                source_type=cached.source_metadata.source_type,
                content_type="text/html",
                title=extract_title(cached.html_content or "") if cached.html_content else None,
                text_content=cached.text_content,
                html_content=cached.html_content,
                content_hash=cached.content_hash,
                cache_key=cached.cache_key,
                warnings=[],
                limitations=["cached content is retrieved, not human verified"],
                requires_human_review=True,
                source_metadata=cached.source_metadata,
                cache_hit=True,
            )

        if request.fixture_path is not None:
            return self._fixture_result(request, request.fixture_path)

        if request.dry_run or not request.live_enabled:
            return self._fake_result(request)

        return self._live_result(request)

    def _fixture_result(self, request: WebFetchRequest, fixture_path: Path) -> WebFetchResult:
        html = fixture_path.read_text(encoding="utf-8")
        result = self._build_result(
            request,
            html,
            RetrievalStatus.RETRIEVED,
            source_type=SourceType.LOCAL_FIXTURE,
            warnings=[],
            limitations=["local HTML fixture; not a live retrieval", "not human verified"],
        )
        self.cache.put_result(result, manual_fixture_mode=True)
        return result

    def _fake_result(self, request: WebFetchRequest) -> WebFetchResult:
        url = str(request.url)
        html = (
            "<html><head><title>Fake Web Fetch</title></head><body>"
            f"<h1>Fake fetch for {url}</h1>"
            "<p>Generated by TuringResearch fake web fetch adapter.</p>"
            "</body></html>"
        )
        status = RetrievalStatus.DRY_RUN if request.dry_run else RetrievalStatus.LIVE_DISABLED
        result = self._build_result(
            request,
            html,
            status,
            source_type=SourceType.FAKE,
            warnings=["fake/default mode; no network access performed"],
            limitations=["retrieved status is not human verification"],
        )
        self.cache.put_result(result, manual_fixture_mode=True)
        return result

    def _live_result(self, request: WebFetchRequest) -> WebFetchResult:
        httpx_module = self._httpx_module()
        if httpx_module is None:
            return self._error_result(
                request,
                RetrievalStatus.ERROR,
                warnings=["httpx is required for live web fetch"],
            )
        try:
            client_factory = self.client_factory or httpx_module.Client
            with client_factory(timeout=request.timeout_seconds, follow_redirects=True) as client:
                response = client.get(str(request.url))
                response.raise_for_status()
                content_type = response.headers.get("content-type", "text/html")
                html = response.text
        except httpx_module.TimeoutException:
            return self._error_result(
                request,
                RetrievalStatus.ERROR,
                warnings=["live web fetch timed out"],
            )
        except httpx_module.HTTPError as exc:
            return self._error_result(
                request,
                RetrievalStatus.ERROR,
                warnings=[f"live web fetch failed: {exc.__class__.__name__}"],
            )
        result = self._build_result(
            request,
            html,
            RetrievalStatus.RETRIEVED,
            source_type=request.source_type,
            warnings=[],
            limitations=["live result is retrieved, not human verified"],
            content_type=content_type,
        )
        self.cache.put_result(result)
        return result

    def _build_result(
        self,
        request: WebFetchRequest,
        html: str,
        status: RetrievalStatus,
        *,
        source_type: SourceType,
        warnings: list[str],
        limitations: list[str],
        content_type: str = "text/html",
    ) -> WebFetchResult:
        url = str(request.url)
        retrieval_time = datetime.now(UTC)
        metadata = build_source_metadata(
            source_url=url,
            content=html,
            provider="web_fetch",
            source_type=source_type,
            source_hygiene_status=request.source_hygiene_status,
            retrieval_time=retrieval_time,
        )
        return WebFetchResult(
            url=url,
            retrieval_status=status,
            retrieval_time=retrieval_time,
            source_type=source_type,
            content_type=content_type,
            title=extract_title(html),
            text_content=html_to_text(html),
            html_content=html,
            content_hash=metadata.content_hash,
            cache_key=build_cache_key(url),
            warnings=warnings,
            limitations=limitations,
            requires_human_review=True,
            source_metadata=metadata,
            cache_hit=False,
        )

    def _error_result(
        self,
        request: WebFetchRequest,
        status: RetrievalStatus,
        *,
        warnings: list[str],
    ) -> WebFetchResult:
        url = str(request.url)
        content = "\n".join(warnings) or status.value
        retrieval_time = datetime.now(UTC)
        metadata = build_source_metadata(
            source_url=url,
            content=content,
            provider="web_fetch",
            source_type=request.source_type,
            source_hygiene_status=request.source_hygiene_status,
            retrieval_time=retrieval_time,
        )
        return WebFetchResult(
            url=url,
            retrieval_status=status,
            retrieval_time=retrieval_time,
            source_type=request.source_type,
            content_type="text/plain",
            title=None,
            text_content=None,
            html_content=None,
            content_hash=hash_text(content),
            cache_key=build_cache_key(url),
            warnings=warnings,
            limitations=["no usable page content retrieved"],
            requires_human_review=True,
            source_metadata=metadata,
            cache_hit=False,
        )

    def _source_hygiene_error(self, request: WebFetchRequest) -> AdapterError | None:
        if request.source_hygiene_status in BLOCKED_HYGIENE:
            return AdapterError(
                code=AdapterErrorCode.SOURCE_HYGIENE_BLOCKED,
                message="web source is not public or authorized",
                provider="web_fetch",
            )
        return None

    def _httpx_module(self) -> Any | None:
        if find_spec("httpx") is None:
            return None
        import httpx  # type: ignore[import-not-found]

        return httpx
