#!/usr/bin/env bash
# shellcheck shell=bash
# build-context-pack.sh - safe local context pack
# Generated by TuringResearch Session script exporter.
# Review before manual execution.
# Safety: fake/dry-run default; no secrets; no destructive commands.
# Safety: no remote execution by default; no automatic Evidence Ledger write.
# MANUAL LIVE STEP (disabled): live SSH/SFTP requires explicit human review.
set -euo pipefail

readonly SOURCE_DIR="examples/session_runtime/context_pack_fixture/source"
readonly OUTPUT_DIR="tmp/session-script-context-pack"
readonly REPORT_PATH="tmp/session-script-pack.md"

python -m turing_research_plus.session_runtime.cli session pack \
  --source-dir "${SOURCE_DIR}" \
  --output-dir "${OUTPUT_DIR}" \
  --output "${REPORT_PATH}"
