#!/usr/bin/env bash
# shellcheck shell=bash
# fake-transfer.sh - local fake transfer
# Generated by TuringResearch Session script exporter.
# Review before manual execution.
# Safety: fake/dry-run default; no secrets; no destructive commands.
# Safety: no remote execution by default; no automatic Evidence Ledger write.
# MANUAL LIVE STEP (disabled): live SSH/SFTP requires explicit human review.
set -euo pipefail

readonly SOURCE_DIR="tmp/session-script-context-pack"
readonly TARGET_DIR="tmp/session-script-fake-transfer"
readonly REPORT_PATH="tmp/session-script-transfer.md"

python -m turing_research_plus.session_runtime.cli session transfer --fake \
  --source-dir "${SOURCE_DIR}" \
  --target-dir "${TARGET_DIR}" \
  --output "${REPORT_PATH}"
