#!/usr/bin/env bash
# shellcheck shell=bash
# preflight.sh - local Session preflight
# Generated by TuringResearch Session script exporter.
# Review before manual execution.
# Safety: fake/dry-run default; no secrets; no destructive commands.
# Safety: no remote execution by default; no automatic Evidence Ledger write.
# MANUAL LIVE STEP (disabled): live SSH/SFTP requires explicit human review.
set -euo pipefail

readonly PROJECT_ROOT="examples/session_runtime/preflight_fixture"
readonly CONTEXT_SOURCE="context"
readonly PREFLIGHT_OUTPUT_DIR="output"
readonly REPORT_PATH="tmp/session-script-preflight.md"

python -m turing_research_plus.session_runtime.cli session preflight \
  --project-root "${PROJECT_ROOT}" \
  --context-source "${CONTEXT_SOURCE}" \
  --output-dir "${PREFLIGHT_OUTPUT_DIR}" \
  --output "${REPORT_PATH}"
