#!/usr/bin/env bash
# shellcheck shell=bash
# verify-return.sh - structured return verifier
# Generated by TuringResearch Session script exporter.
# Review before manual execution.
# Safety: fake/dry-run default; no secrets; no destructive commands.
# Safety: no remote execution by default; no automatic Evidence Ledger write.
# MANUAL LIVE STEP (disabled): live SSH/SFTP requires explicit human review.
set -euo pipefail

readonly RETURN_DIR="examples/session_runtime/return_fixture"
readonly REPORT_PATH="tmp/session-script-return.md"

python -m turing_research_plus.session_runtime.cli session verify-return \
  --return-dir "${RETURN_DIR}" \
  --output "${REPORT_PATH}"
