#!/usr/bin/env bash
# shellcheck shell=bash
# workflow-replay.sh - full fake workflow replay
# Generated by TuringResearch Session script exporter.
# Review before manual execution.
# Safety: fake/dry-run default; no secrets; no destructive commands.
# Safety: no remote execution by default; no automatic Evidence Ledger write.
# MANUAL LIVE STEP (disabled): live SSH/SFTP requires explicit human review.
set -euo pipefail

readonly PROJECT_ROOT="examples/session_runtime/preflight_fixture"
readonly PREFLIGHT_CONTEXT_SOURCE="context"
readonly PREFLIGHT_OUTPUT_DIR="output"
readonly CONTEXT_PACK_SOURCE_DIR="examples/session_runtime/context_pack_fixture/source"
readonly REPLAY_WORKSPACE="tmp/session-script-replay"
readonly FAKE_RETURN_FIXTURE_DIR="examples/session_runtime/return_fixture"
readonly REPORT_PATH="tmp/session-script-replay.md"

python -m turing_research_plus.session_runtime.cli session replay \
  --project-root "${PROJECT_ROOT}" \
  --preflight-context-source "${PREFLIGHT_CONTEXT_SOURCE}" \
  --preflight-output-dir "${PREFLIGHT_OUTPUT_DIR}" \
  --context-pack-source-dir "${CONTEXT_PACK_SOURCE_DIR}" \
  --replay-workspace "${REPLAY_WORKSPACE}" \
  --fake-return-fixture-dir "${FAKE_RETURN_FIXTURE_DIR}" \
  --output "${REPORT_PATH}"
