"""Adapter protocol package for TuringResearch Plus."""

from turing_research_plus.adapters.errors import AdapterError, AdapterErrorCode
from turing_research_plus.adapters.fake import (
    FakeApifyWebAdapter,
    FakeArxivAdapter,
    FakeOpenAICompatibleLLMAdapter,
    FakePDFConverterAdapter,
    FakeSemanticScholarAdapter,
    FakeWebFetchAdapter,
    FakeWebSearchAdapter,
)
from turing_research_plus.adapters.models import (
    AdapterCachePolicy,
    AdapterRequestContext,
    AdapterRetryPolicy,
    AdapterTimeoutPolicy,
    ArxivQuery,
    ArxivSearchResult,
    LLMCompletionRequest,
    LLMCompletionResult,
    PDFConversionRequest,
    PDFConversionResult,
    RateLimitPolicy,
    SemanticScholarAuthorLookup,
    SemanticScholarAuthorResult,
    SemanticScholarPaperBatchLookup,
    SemanticScholarPaperIdLookup,
    SemanticScholarPaperListLookup,
    SemanticScholarPaperLookup,
    SemanticScholarPaperResult,
    SemanticScholarRecommendationLookup,
    SourceMetadata,
    WebFetchRequest,
    WebFetchResult,
    WebSearchRequest,
    WebSearchResult,
)
from turing_research_plus.adapters.protocols import (
    ApifyWebAdapter,
    ArxivAdapter,
    OpenAICompatibleLLMAdapter,
    PDFConverterAdapter,
    SemanticScholarAdapter,
    WebFetchAdapter,
    WebSearchAdapter,
)
from turing_research_plus.adapters.semantic_scholar import SemanticScholarLiveAdapter

__all__ = [
    "AdapterCachePolicy",
    "AdapterError",
    "AdapterErrorCode",
    "AdapterRequestContext",
    "AdapterRetryPolicy",
    "AdapterTimeoutPolicy",
    "ApifyWebAdapter",
    "ArxivAdapter",
    "ArxivQuery",
    "ArxivSearchResult",
    "FakeApifyWebAdapter",
    "FakeArxivAdapter",
    "FakeOpenAICompatibleLLMAdapter",
    "FakePDFConverterAdapter",
    "FakeSemanticScholarAdapter",
    "FakeWebFetchAdapter",
    "FakeWebSearchAdapter",
    "LLMCompletionRequest",
    "LLMCompletionResult",
    "OpenAICompatibleLLMAdapter",
    "PDFConversionRequest",
    "PDFConversionResult",
    "PDFConverterAdapter",
    "RateLimitPolicy",
    "SemanticScholarAuthorLookup",
    "SemanticScholarAuthorResult",
    "SemanticScholarAdapter",
    "SemanticScholarLiveAdapter",
    "SemanticScholarPaperBatchLookup",
    "SemanticScholarPaperIdLookup",
    "SemanticScholarPaperListLookup",
    "SemanticScholarPaperLookup",
    "SemanticScholarPaperResult",
    "SemanticScholarRecommendationLookup",
    "SourceMetadata",
    "WebFetchAdapter",
    "WebFetchRequest",
    "WebFetchResult",
    "WebSearchAdapter",
    "WebSearchRequest",
    "WebSearchResult",
]
